from sqlmodel import Session, select
from app.infrastructure.db.sqlite_client import engine
from app.domain.models.district_metric import DistrictMetric

def seed_district_metrics():
    with Session(engine) as session:
        statement = select(DistrictMetric)
        existing = session.exec(statement).first()
        if not existing:
            metrics = [
                DistrictMetric(
                    name="North West",
                    status="STABLE",
                    complaints_total=48, complaints_sanitation=15, complaints_water=12, complaints_roads=14, complaints_electricity=7,
                    solved_total=38, solved_sanitation=12, solved_water=10, solved_roads=11, solved_electricity=5,
                    active_total=10, active_sanitation=3, active_water=2, active_roads=3, active_electricity=2,
                    avg_response="24h",
                    escalations=1,
                    alerts_health=1,
                    alerts_education=2,
                    project_name="Outer Ring Drainage",
                    project_status="Active",
                    officer_sanitation="Mr. Rajeev Kumar (MCD Sanitation Division)",
                    officer_water="Mr. S. K. Dwivedi (Delhi Jal Board - West)",
                    officer_roads="Mr. Vinod Prasad (PWD NW Zone)",
                    officer_electricity="Mr. Ramesh Saxena (Tata Power DDL)"
                ),
                DistrictMetric(
                    name="North",
                    status="STABLE",
                    complaints_total=12, complaints_sanitation=3, complaints_water=4, complaints_roads=3, complaints_electricity=2,
                    solved_total=10, solved_sanitation=3, solved_water=3, solved_roads=2, solved_electricity=2,
                    active_total=2, active_sanitation=0, active_water=1, active_roads=1, active_electricity=0,
                    avg_response="12h",
                    escalations=0,
                    alerts_health=0,
                    alerts_education=0,
                    project_name="Heritage Wall Conservation",
                    project_status="Completed",
                    officer_sanitation="Mrs. Anjali Roy (MCD North Zone)",
                    officer_water="Mr. S. K. Bose (DJB North Zone)",
                    officer_roads="Mr. P. K. Singh (PWD North)",
                    officer_electricity="Mr. Sanjay Dutt (Tata Power)"
                ),
                DistrictMetric(
                    name="North East",
                    status="STABLE",
                    complaints_total=35, complaints_sanitation=12, complaints_water=8, complaints_roads=10, complaints_electricity=5,
                    solved_total=28, solved_sanitation=10, solved_water=6, solved_roads=8, solved_electricity=4,
                    active_total=7, active_sanitation=2, active_water=2, active_roads=2, active_electricity=1,
                    avg_response="36h",
                    escalations=1,
                    alerts_health=1,
                    alerts_education=1,
                    project_name="Yamuna East Embankment",
                    project_status="Active",
                    officer_sanitation="Mr. Satish Pal (MCD NE Zone)",
                    officer_water="Mr. V. K. Jain (DJB East)",
                    officer_roads="Mr. S. C. Verma (MCD Works Dept)",
                    officer_electricity="Mr. J. K. Gupta (BSES Yamuna)"
                ),
                DistrictMetric(
                    name="Shahdara",
                    status="STABLE",
                    complaints_total=29, complaints_sanitation=9, complaints_water=7, complaints_roads=8, complaints_electricity=5,
                    solved_total=22, solved_sanitation=7, solved_water=5, solved_roads=6, solved_electricity=4,
                    active_total=7, active_sanitation=2, active_water=2, active_roads=2, active_electricity=1,
                    avg_response="28h",
                    escalations=0,
                    alerts_health=0,
                    alerts_education=1,
                    project_name="N/A",
                    project_status="None",
                    officer_sanitation="Mr. Amit Sharma (MCD Shahdara)",
                    officer_water="Mr. R. K. Mishra (DJB Shahdara)",
                    officer_roads="Mr. L. N. Rao (MCD Works)",
                    officer_electricity="Mr. Naveen Lal (BSES Yamuna)"
                ),
                DistrictMetric(
                    name="East",
                    status="STABLE",
                    complaints_total=41, complaints_sanitation=14, complaints_water=10, complaints_roads=12, complaints_electricity=5,
                    solved_total=32, solved_sanitation=11, solved_water=8, solved_roads=9, solved_electricity=4,
                    active_total=9, active_sanitation=3, active_water=2, active_roads=3, active_electricity=1,
                    avg_response="30h",
                    escalations=1,
                    alerts_health=2,
                    alerts_education=1,
                    project_name="Mayur Vihar Flyover Expansion",
                    project_status="Active",
                    officer_sanitation="Ms. Neha Gupta (MCD East Zone)",
                    officer_water="Mr. H. S. Rawat (DJB East)",
                    officer_roads="Mr. P. R. Chawla (PWD East)",
                    officer_electricity="Mr. A. K. Joshi (BSES Yamuna)"
                ),
                DistrictMetric(
                    name="West",
                    status="STABLE",
                    complaints_total=52, complaints_sanitation=18, complaints_water=14, complaints_roads=12, complaints_electricity=8,
                    solved_total=40, solved_sanitation=14, solved_water=11, solved_roads=9, solved_electricity=6,
                    active_total=12, active_sanitation=4, active_water=3, active_roads=3, active_electricity=2,
                    avg_response="26h",
                    escalations=2,
                    alerts_health=1,
                    alerts_education=3,
                    project_name="Janakpuri Community Park",
                    project_status="Completed",
                    officer_sanitation="Mr. Vinay Yadav (MCD West Zone)",
                    officer_water="Mr. Anil Nair (DJB West)",
                    officer_roads="Mr. S. K. Grover (PWD West)",
                    officer_electricity="Mr. R. S. Negi (BSES Rajdhani)"
                ),
                DistrictMetric(
                    name="Central",
                    status="CRITICAL",
                    complaints_total=138, complaints_sanitation=45, complaints_water=38, complaints_roads=35, complaints_electricity=20,
                    solved_total=92, solved_sanitation=30, solved_water=25, solved_roads=24, solved_electricity=13,
                    active_total=46, active_sanitation=15, active_water=13, active_roads=11, active_electricity=7,
                    avg_response="48h",
                    escalations=8,
                    alerts_health=7,
                    alerts_education=4,
                    project_name="Walled City Sanitation Drive",
                    project_status="Active",
                    officer_sanitation="Mr. Manoj Dwivedi (Executive Engineer, MCD Central Zone)",
                    officer_water="Mr. Rajesh Saxena (Superintendent Engineer, DJB Central)",
                    officer_roads="Mr. P. S. Oberoi (Executive Engineer, PWD Central)",
                    officer_electricity="Mr. V. K. Aggarwal (General Manager, BSES Yamuna)"
                ),
                DistrictMetric(
                    name="New Delhi",
                    status="STABLE",
                    complaints_total=67, complaints_sanitation=20, complaints_water=18, complaints_roads=15, complaints_electricity=14,
                    solved_total=52, solved_sanitation=16, solved_water=14, solved_roads=12, solved_electricity=10,
                    active_total=15, active_sanitation=4, active_water=4, active_roads=3, active_electricity=4,
                    avg_response="18h",
                    escalations=2,
                    alerts_health=2,
                    alerts_education=1,
                    project_name="Kartavya Path Landscaping",
                    project_status="Active",
                    officer_sanitation="Mr. Sanjay Malhotra (Director of Health, NDMC)",
                    officer_water="Mr. Ramesh Lal (Chief Civil Engineer, NDMC)",
                    officer_roads="Mr. Amit Sen (Chief Road Engineer, NDMC)",
                    officer_electricity="Mr. Anil Mehta (Director of Power, NDMC)"
                ),
                DistrictMetric(
                    name="South West",
                    status="STABLE",
                    complaints_total=33, complaints_sanitation=10, complaints_water=9, complaints_roads=9, complaints_electricity=5,
                    solved_total=27, solved_sanitation=8, solved_water=8, solved_roads=7, solved_electricity=4,
                    active_total=6, active_sanitation=2, active_water=1, active_roads=2, active_electricity=1,
                    avg_response="22h",
                    escalations=0,
                    alerts_health=1,
                    alerts_education=0,
                    project_name="Dwarka Sector 21 School",
                    project_status="Pending",
                    officer_sanitation="Mr. K. S. Rao (MCD SW Zone Director)",
                    officer_water="Mr. T. C. Sharma (DJB SW Executive)",
                    officer_roads="Mr. Rohit Gupta (MCD Works SW)",
                    officer_electricity="Mr. Devendra Pal (BSES Rajdhani)"
                ),
                DistrictMetric(
                    name="South",
                    status="CRITICAL",
                    complaints_total=92, complaints_sanitation=30, complaints_water=24, complaints_roads=23, complaints_electricity=15,
                    solved_total=66, solved_sanitation=22, solved_water=16, solved_roads=17, solved_electricity=11,
                    active_total=26, active_sanitation=8, active_water=8, active_roads=6, active_electricity=4,
                    avg_response="38h",
                    escalations=4,
                    alerts_health=4,
                    alerts_education=2,
                    project_name="Saket Smart Hub Integration",
                    project_status="Active",
                    officer_sanitation="Ms. Aarti Sharma (Executive Engineer, MCD South)",
                    officer_water="Mr. S. K. Nair (Superintendent Engineer, DJB South)",
                    officer_roads="Mr. Manoj Rawat (Executive Engineer, PWD South)",
                    officer_electricity="Mr. Amit Bhatia (General Manager, BSES Rajdhani)"
                ),
                DistrictMetric(
                    name="South East",
                    status="STABLE",
                    complaints_total=44, complaints_sanitation=15, complaints_water=11, complaints_roads=12, complaints_electricity=6,
                    solved_total=34, solved_sanitation=12, solved_water=8, solved_roads=9, solved_electricity=5,
                    active_total=10, active_sanitation=3, active_water=3, active_roads=3, active_electricity=1,
                    avg_response="32h",
                    escalations=1,
                    alerts_health=2,
                    alerts_education=0,
                    project_name="Okhla STP Upgradation",
                    project_status="Pending",
                    officer_sanitation="Mr. Rajesh Tiwari (MCD SE Zone)",
                    officer_water="Mr. K. K. Sharma (DJB SE Executive)",
                    officer_roads="Mr. S. P. Yadav (PWD SE)",
                    officer_electricity="Mr. R. K. Mittal (BSES Rajdhani)"
                )
            ]
            session.add_all(metrics)
            session.commit()
            print("District metrics seeded successfully!")
